module m2m
{

    interface ServiceEnabler
    {

        void recordPeer(in string peerName);

    };

    interface Machine2Machine
    {
        string sendMsg2Machine(in string msg, in string machine);
    };

};