module m2m
{
    typedef sequence<string> peerList;

    interface ServiceEnabler
    {

        string recordPeer(in string peerName);
        peerList getConnectedPeers();

    };

    interface Peer2Peer
    {
        oneway void sendMsg2Peer(in string msg, in string peer);
    };

};