module m2m
{
    typedef sequence<string> peerList;

    interface ServiceEnabler
    {

        void recordPeer(in string peerName);
        peerList getConnectedPeers();

    };

    interface Peer2Peer
    {
        string sendMsg2Peer(in string msg, in string peer);
    };

};