module m2m
{

    interface ServiceEnabler
    {

        void recordPeer(in string peerName);
        void getConnectedPeers();

    };

    interface Peer2Peer
    {
        string sendMsg2Peer(in string msg, in string peer);
    };

};