module servants
{
    exception NameAlreadyUsed {};
    exception UnknownPeer {};

    typedef sequence<string> List;

    interface Server
    {
        void join(in string name) raises (NameAlreadyUsed);
        void leave(in string name) raises (UnknownPeer);
        List getConnectedPeers();
        string genKeyPair(in string peerName, in unsigned long vDays,
                          in unsigned long nbits, in string sKey);
    };

    interface Peer
    {
        string getName();
        oneway void send(in string message, in string peer);
    };
};